apiVersion: v2
name: nifi
description: "[TESTING] Apache NiFi, PostgreSQL, NiFi Registry, and TDC"
type: application
version: "0.2.2"
appVersion: "2.3.0"
home: https://github.com/EUCAIM/etl-toolset/
icon: https://nifi.apache.org/images/apache-nifi-logo.svg
#icon: https://nifi.apache.org/images/apache-nifi-drop-logo.svg
sources:
 - https://github.com/EUCAIM/etl-toolset/tree/Reference_Node
maintainers:
  - name: Bahia Software
    #email: ?
