
# Put here the ID of dataset you are going to work with (you can put more than one separated by comas):
datasetsList: ""


# ======= ADVANCED PARAMETERS (usually you don't need to change them)
nifi:
  image:
    repository: harbor.eucaim-node.i3m.upv.es:5000/dockerhub/apache/nifi
    tag: "2.3.0"
  service:
    port: 8443
  credentials:
    username: eucaim
    password: ""   # leave empty to generate a random one
  localIp: "127.0.0.1"
nifiRegistry:
  image:
    repository: harbor.eucaim-node.i3m.upv.es:5000/dockerhub/apache/nifi-registry
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 18080
postgresql:
  image:
    repository: harbor.eucaim-node.i3m.upv.es:5000/library/etl/postgres-etl
    tag: "15-1"
  user: postgres
  password: postgres
  database: eucaim-etl-db
tdc:
  image: 
    repository: harbor.eucaim-node.i3m.upv.es:5000/library/etl/tdc-app
    tag: "1.0-slim"
    pullPolicy: IfNotPresent
  service:
    port: 5000
  containerPort: 5000
desktop:
  image:
    repository: harbor.eucaim-node.i3m.upv.es:5000/library/etl/desktop
    tag: "1.1"
