apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi.name" . }}-nifi
  annotations: 
    chaimeleon.eu/toolName: "{{ .Chart.Name }}"
    chaimeleon.eu/toolVersion: "{{ .Chart.Version }}"
    chaimeleon.eu/persistentHomeMountPoint: "/mnt/persistent-home"
    chaimeleon.eu/persistentSharedFolderMountPoint: "/mnt/persistent-shared-folder"
{{- if .Values.datasetsList }}
#   chaimeleon.eu/datasetsIDs: "{{ .Values.datasetsList }}"
#   chaimeleon.eu/datasetsMountPoint: "/mnt/datasets"
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nifi.name" . }}
      component: nifi
  template:
    metadata:
      labels:
        app: {{ include "nifi.name" . }}
        component: nifi
    spec:
      containers:
        - name: nifi
          image: "{{ .Values.nifi.image.repository }}:{{ .Values.nifi.image.tag }}"
          ports:
            - containerPort: 8443
          env:
            - name: SINGLE_USER_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ include "nifi.name" . }}-nifi"
                  key: username
            - name: SINGLE_USER_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "nifi.name" . }}-nifi"
                  key: password
            - name: NIFI_WEB_PROXY_HOST
              value: "{{ include "nifi.name" . }}-nifi:8443,{{ .Values.nifi.localIp }}:8443"
            - name: NIFI_WEB_HTTPS_PORT
              value: "8443"
            - name: NIFI_WEB_PROXY_CONTEXT_PATH
              value: "/"
            - name: ETL_HOME
              value: "/mnt/persistent-home/ETL-files"
            - name: ETL_RESOURCES
              value: "/mnt/persistent-shared-folder/apps/etl"
            #- name: NIFI_WEB_HTTPS_HOST
            #  value: "localhost"
            - name: SHARED_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "shared-sql-db-auth"
                  key: host
            - name: SHARED_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "shared-sql-db-auth"
                  key: user
            - name: SHARED_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "shared-sql-db-auth"
                  key: password
            - name: SHARED_DB_NAME
              value: "project-{{ .Values.projectCode }}--{{ .Values.subprojectCode }}"
          command: 
          - "sh"
          - "-c"
          - >-
            mkdir -p $ETL_HOME/nifi_data/nifi_data
            && mkdir -p $ETL_HOME/nifi_data/nifi_database_repository
            && mkdir -p $ETL_HOME/nifi_data/nifi_flowfile_repository
            && mkdir -p $ETL_HOME/nifi_data/nifi_content_repository
            && mkdir -p $ETL_HOME/nifi_data/nifi_provenance_repository
            && mkdir -p $ETL_HOME/input_data
            && mkdir -p $ETL_HOME/output_data
            && mkdir -p $ETL_HOME/staging_data/curated_as_csv/clinical_data
            && mkdir -p $ETL_HOME/staging_data/input_as_csv/clinical_data
            && mkdir -p $ETL_HOME/staging_data/input_as_csv/image_metadata
            && mkdir -p $ETL_HOME/TDC_Output
            && ln -s $ETL_HOME/nifi_data/nifi_data                  /opt/nifi/nifi-current/data
            && ln -s $ETL_HOME/nifi_data/nifi_database_repository   /opt/nifi/nifi-current/database_repository
            && ln -s $ETL_HOME/nifi_data/nifi_flowfile_repository   /opt/nifi/nifi-current/flowfile_repository
            && ln -s $ETL_HOME/nifi_data/nifi_content_repository    /opt/nifi/nifi-current/content_repository
            && ln -s $ETL_HOME/nifi_data/nifi_provenance_repository /opt/nifi/nifi-current/provenance_repository
            && ln -s $ETL_RESOURCES/flows         /opt/nifi/flows
            && ln -s $ETL_RESOURCES/truststore.jks        /opt/nifi/truststore.jks
            && ln -s $ETL_RESOURCES/keystore.jks          /opt/nifi/keystore.jks
            && (/bin/bash $ETL_RESOURCES/init.sh & exec /opt/nifi/scripts/start.sh )
            