apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "nifi.name" . }}-nifi"
type: Opaque
stringData:
  username: "{{ .Values.nifi.credentials.username }}"
{{- if .Values.nifi.credentials.password }}
  password: "{{ .Values.nifi.credentials.password }}"
{{- else }}
  password: "{{ include "utils.randomString" . }}"
{{- end }}
