apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.name" . }}-nifi
spec:
  selector:
    app: {{ include "nifi.name" . }}
    component: nifi
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.nifi.service.port }}
      targetPort: 8443
