apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi.name" . }}-postgres
  annotations: 
    chaimeleon.eu/toolName: "{{ .Chart.Name }}"
    chaimeleon.eu/toolVersion: "{{ .Chart.Version }}"
    chaimeleon.eu/persistentHomeMountPoint: "/mnt/persistent-home"
    chaimeleon.eu/persistentSharedFolderMountPoint: "/mnt/persistent-shared-folder"
  labels:
    app: {{ include "nifi.name" . }}
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nifi.name" . }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ include "nifi.name" . }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: POSTGRES_PASSWORD
            - name:  POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name:  PGDATA
              value: "/mnt/persistent-home/ETL-files/postgresql_data/data"
          command: 
          - "sh"
          - "-c"
          - >-
            mkdir -p $PGDATA
            && docker-entrypoint.sh postgres

