apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.name" . }}-postgres
spec:
  selector:
    app: {{ include "nifi.name" . }}
    component: postgres
  type: ClusterIP
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
