apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi.name" . }}-registry
  annotations: 
    chaimeleon.eu/toolName: "{{ .Chart.Name }}"
    chaimeleon.eu/toolVersion: "{{ .Chart.Version }}"
    chaimeleon.eu/persistentHomeMountPoint: "/mnt/persistent-home"
    chaimeleon.eu/persistentSharedFolderMountPoint: "/mnt/persistent-shared-folder"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nifi.name" . }}
      component: registry
  template:
    metadata:
      labels:
        app: {{ include "nifi.name" . }}
        component: registry
    env:
    - name: NIFI_REGISTRY_WEB_PROXY_HOST
      value: "localhost:18080"
    spec:
      hostname: {{ include "nifi.name" . }}-registry
      containers:
        - name: nifi-registry
          image: "{{ .Values.nifiRegistry.image.repository }}:{{ .Values.nifiRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.nifiRegistry.image.pullPolicy }}
          command: 
          - "sh"
          - "-c"
          - >-
            mkdir -p /mnt/persistent-home/ETL-files/registry/flow-storage
            && mkdir -p /mnt/persistent-home/ETL-files/registry/database
            && ln -s /mnt/persistent-home/ETL-files/registry/flow-storage /opt/nifi-registry/nifi-registry-current/flow_storage
            && ln -s /mnt/persistent-home/ETL-files/registry/database /opt/nifi-registry/nifi-registry-current/database
            && ../scripts/start.sh
          ports:
            - containerPort: 18080
