apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi-registry.name" . }}-registry
  labels:
    app: {{ include "nifi-registry.name" . }}-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nifi-registry.name" . }}-registry
  template:
    metadata:
      labels:
        app: {{ include "nifi-registry.name" . }}-registry
    env:
    - name: NIFI_REGISTRY_WEB_PROXY_HOST
      value: "localhost:18080"
    spec:
      hostname: {{ include "nifi-registry.name" . }}-registry
      containers:
        - name: nifi-registry
          image: "{{ .Values.nifiRegistry.image.repository }}:{{ .Values.nifiRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.nifiRegistry.image.pullPolicy }}
          ports:
            - containerPort: 18080
annotations: 
    chaimeleon.eu/toolName: "{{ .Chart.Name }}"
    chaimeleon.eu/toolVersion: "{{ .Chart.Version }}"
    
    chaimeleon.eu/datasetsIDs: "{{ .Values.datasets_list }}"
    chaimeleon.eu/datasetsMountPoint: "{{ include "platform.datasets.mount_point" . }}"
    
    chaimeleon.eu/persistentHomeMountPoint: "{{ include "platform.persistent_home.mount_point" . }}"
    chaimeleon.eu/persistentSharedFolderMountPoint: "{{ include "platform.persistent_shared_folder.mount_point" . }}"
    
    chaimeleon.eu/createGuacamoleConnection: "true"
