apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi.name" . }}-tdc
  labels:
    app: {{ include "nifi.name" . }}
    component: tdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nifi.name" . }}-tdc
  template:
    metadata:
      labels:
        app: {{ include "nifi.name" . }}-tdc
    spec:
      containers:
        - name: tdc
          image: "{{ .Values.tdc.image.repository }}:{{ .Values.tdc.image.tag }}"
          imagePullPolicy: {{ .Values.tdc.image.pullPolicy }}
          ports:
        - containerPort: {{ .Values.containerPort }}
