apiVersion: v1
kind: Secret
metadata:
  name: nifi-keystores
type: Opaque
data:
  keystore.jks: {{ .Files.Get "files/keystore.jks" | b64enc }}
  truststore.jks: {{ .Files.Get "files/truststore.jks" | b64enc }}
  flows.zip: {{ .Files.Get "files/flows.zip" | b64enc }}
  scripts.zip: {{ .Files.Get "files/scripts.zip" | b64enc }}
  postgresql-42.7.4.zip: {{ (.Files.Glob "files/postgresql-42.7.4.jar").AsConfig | indent 2 }}
