apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.name" . }}-nifi
  labels:
    app: {{ include "nifi.name" . }}
    component: nifi
spec:
  selector:
    app: {{ include "nifi.name" . }}
    component: nifi
  ports:
    - protocol: TCP
      port: {{ .Values.nifi.service.port }}
      targetPort: {{ .Values.nifi.service.port }}
  type: ClusterIP

