apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi-registry.name" . }}-registry
  labels:
    app: {{ include "nifi-registry.name" . }}-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nifi-registry.name" . }}-registry
  template:
    metadata:
      labels:
        app: {{ include "nifi-registry.name" . }}-registry
    env:
    - name: NIFI_REGISTRY_WEB_PROXY_HOST
      value: "localhost:18080"
    spec:
      hostname: {{ include "nifi-registry.name" . }}-registry
      containers:
        - name: nifi-registry
          image: "{{ .Values.nifiRegistry.image.repository }}:{{ .Values.nifiRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.nifiRegistry.image.pullPolicy }}
          ports:
            - containerPort: 18080
          volumeMounts:
            - name: flow-storage
              mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
            - name: database
              mountPath: /opt/nifi-registry/nifi-registry-current/database
      volumes:
        - name: flow-storage
          persistentVolumeClaim:
            claimName: {{ include "nifi-registry.name" . }}-flow-storage
        - name: database
          persistentVolumeClaim:
            claimName: {{ include "nifi-registry.name" . }}-database