name: Test NiFi Pipelines

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Launch environment
        run: ./startup.sh

      - name: Esperar a que init termine
        run: |
          CONTAINER=$(docker compose ps -q nifi)

          echo "Waiting for: init.sh"

          until docker exec $CONTAINER sh -c '[ -f /tmp/init_done ]'; do
            echo "Not ready yet..."
            sleep 5
          done

          echo "Init complete ✅"

      - name: Run tests
        run: ./scripts/run_tests.sh

      - name: Apagar entorno
        if: always()
        run: docker compose down -v